version: '3'
services:
  server:
    build: .
    container_name: the-league-graphql-server
    ports:
      - "5000:5000" # Expose the app on port 5000 internally
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: football-club-nginx
    ports:
      - "80:80"
    volumes:
      - /root/web_applications/nginx-configs/sites-enabled/manage-theleague.conf:/etc/nginx/conf.d/manage-theleague.conf
    depends_on:
      - server
    